--------------------------------
-- Estates
--------------------------------
NDefines.NGame.MAX_ESTATE_COUNTRIES = 50

NDefines.NCountry.ALLOW_ESTATE_AND_PARLIAMENT_SEAT_IN_PROVINCE = 1
NDefines.NCountry.ALLOW_ESTATE_IN_CAPITAL = 1

NDefines.NCountry.ESTATE_ANGRY_THRESHOLD = 30
NDefines.NCountry.ESTATE_HAPPY_THRESHOLD = 70

NDefines.NCountry.ESTATE_LOYALTY_DECAY_BASE_MIN = 0.5
NDefines.NCountry.ESTATE_LOYALTY_DECAY_BASE_MAX = 1

NDefines.NCountry.ESTATE_INFLUENCE_LEVEL_1 = 30
NDefines.NCountry.ESTATE_INFLUENCE_LEVEL_2 = 50
NDefines.NCountry.ESTATE_INFLUENCE_LEVEL_3 = 70

NDefines.NCountry.ESTATE_PROVINCE_HAPPINESS_INCREASE = 1.0 
NDefines.NCountry.ESTATE_PROVINCE_HAPPINESS_DECREASE = 1.0 
NDefines.NCountry.ESTATE_PROVINCE_HAPPINESS_CHANGE_MAX_POS = 25 
NDefines.NCountry.ESTATE_PROVINCE_HAPPINESS_CHANGE_MAX_NEG = 25 

NDefines.NCountry.ESTATE_PROVINCE_POWER = 1.5
NDefines.NCountry.ESTATE_PROVINCE_POWER_MAX = 50
NDefines.NCountry.ESTATE_DANGER_THRESHOLD = 100
NDefines.NCountry.ESTATE_GRANT_PROVINCE_COOLDOWN = 5

NDefines.NAI.DANGEROUS_ESTATE_INFLUENCE_BUFFER = 5.0