--------------------------------
-- Exploration
--------------------------------
NDefines.NCountry.EXPLORE_COAST_EVENT_CHANCE = 10
NDefines.NCountry.MIN_TECH_FOR_CIRCUMNAVIGATE = 20
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_1 = 887
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_2 = 1045
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_3 = 1019
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_4 = 1113
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_5 = 1637
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_6 = 1564
NDefines.NCountry.MIN_SHIPS_TO_EXPLORE = 3

