--------------------------------
-- Ranks
--------------------------------
NDefines.NCountry.MAX_GOV_RANK = 10

NDefines.NCountry.CULTURAL_UNION_MIN_RANK = 10

NDefines.NCountry.PRESTIGE_GAIN_FOR_GOV_RANK_2 = 25
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_2 = 75
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_2 = 250
NDefines.NCountry.PRESTIGE_GAIN_FOR_GOV_RANK_3 = 25
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_3 = 75
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_3 = 500
NDefines.NCountry.PRESTIGE_GAIN_FOR_GOV_RANK_X = 25
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_X = 75
NDefines.NCountry.ADDITIONAL_MIN_DEVELOPMENT_FOR_GOV_RANK_X = 250

NDefines.NCountry.NAT_FOCUS_YEARS_RANK = 2

--------------------------------
-- Government Reforms
--------------------------------
NDefines.NGovernment.LEGACY_NATIVES_REFORM_REPUBLIC_SPONSOR = "republic_reform"
NDefines.NGovernment.LEGACY_NATIVES_REFORM_MONARCHY_SPONSOR = "kingdom_reform"
NDefines.NGovernment.LEGACY_NATIVES_REFORM_THEOCRACY_SPONSOR = "theocracy_reform"
NDefines.NGovernment.GOVERNMENT_REFORM_BASE_COST = 100.0
NDefines.NGovernment.GOVERNMENT_REFORM_COST_INCREASE = 100.0 -- Disable
NDefines.NGovernment.GOVERNMENT_REFORM_CHANGE_CORRUPTION = 0.0 -- Disable
NDefines.NGovernment.GOVERNMENT_REFORM_CHANGE_MAX_CORRUPTION = 200.0 -- Disable
NDefines.NGovernment.GOVERNMENT_REFORM_YEARLY_BASE_PROGRESS = 1.0
NDefines.NGovernment.GOVERNMENT_REFORM_HISTORIC_AUTONOMY = 0.0

--------------------------------
-- Abilities
--------------------------------
NDefines.NGovernment.RUSSIAN_ABILITY_COST = 100
NDefines.NGovernment.RUSSIAN_ABILITY_POOL_SIZE = 150
NDefines.NGovernment.RUSSIAN_ABILITY_BASE_GAIN = 3

NDefines.NGovernment.RUSSIAN_ABILITY_SUBEDNIK_MIN_AUTONOMY = 10
NDefines.NGovernment.RUSSIAN_ABILITY_SUBEDNIK_AUTONOMY_CHANGE = -10
NDefines.NGovernment.RUSSIAN_ABILITY_OPRICHNINA_THRESHOLD = 0.3
NDefines.NGovernment.RUSSIAN_ABILITY_OPRICHNINA_AI_THRESHOLD = 0.85 -- AI will use ability when revolt risk is 90%, or when they have full power
NDefines.NGovernment.RUSSIAN_ABILITY_OPRICHNINA_CHANGE = -0.3
NDefines.NGovernment.RUSSIAN_ABILITY_STRELTSY_WE_CHANGE = -2
NDefines.NGovernment.RUSSIAN_ABILITY_STRELTSY_SPAWN_SIZE = 0.2

NDefines.NGovernment.IQTA_POLICY_COOLDOWN_YEARS = 20
NDefines.NGovernment.EFFICIENT_FARMING_DUCAT_MULTIPLIER = 2
NDefines.NGovernment.LAND_AQUISITION_MANPOWER_MULTIPLIER = 0.05

NDefines.NGovernment.SEIZE_CLERICAL_HOLDINGS_COST = 100
NDefines.NGovernment.INVITE_MINORITIES_COST = 100
NDefines.NGovernment.SANCTION_HOLY_WAR_COST = 100
NDefines.NGovernment.FEUDAL_THEOCRACY_INTERACTION_COOLDOWN_YEARS = 5
NDefines.NGovernment.SANCTION_HOLY_WAR_LIST_SIZE = 7
NDefines.NGovernment.INVITE_MINORITIES_GAIN = 1

NDefines.NGovernment.MAMLUK_ABILITY_POOL_SIZE = 150
NDefines.NGovernment.MAMLUK_ABILITY_COST = 100
NDefines.NGovernment.MAMLUK_RECRUIT_MANPOWER_MULTIPLIER = 100
NDefines.NGovernment.MAMLUK_SELL_SLAVES_DUCATS_MULTIPLIER = 10
NDefines.NGovernment.PROMOTE_MAMLUK_CULTURE_DURATION_YEARS = 1

NDefines.NGovernment.TRAIN_HORSEMANSHIP_DURATION_YEARS = 5
NDefines.NGovernment.CONSCRIPT_FROM_TRIBES_AMOUNT = 5
NDefines.NGovernment.CONSCRIPT_FROM_TRIBES_TIME = 0.25
NDefines.NGovernment.TRIBAL_ALLEGIANCE_MAX = 100
NDefines.NGovernment.TRIBAL_ALLEGIANCE_HUMILIATE = 30.0
NDefines.NGovernment.TRIBAL_FEDERATION_ABILITY_COST = 50
NDefines.NGovernment.ENLIST_GENERAL_TRADITION = 50
